# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-25 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_auto_20170325_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, verbose_name='Subject')),
                ('stage', models.CharField(choices=[('new', 'New'), ('dead', 'Dead')], default='new', max_length=5, verbose_name='Stage')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('veryhigh', 'Very High')], default='normal', max_length=10, verbose_name='Priority')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('mobile', models.BigIntegerField(blank=True, verbose_name='Mobile')),
                ('fax', models.IntegerField(blank=True, verbose_name='Fax')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Customer', verbose_name='Customer')),
            ],
        ),
    ]
