# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-26 07:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_auto_20170325_2350'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmlead',
            name='city',
            field=models.CharField(blank=True, max_length=250, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Country'),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created'),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sales Person'),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.State', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='street',
            field=models.CharField(blank=True, max_length=300, verbose_name='Lane'),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='street2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='zip_code',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Zip Code'),
        ),
    ]
