# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0003_auto_20170426_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name=b'Product Name')),
                ('sell_ok', models.BooleanField(verbose_name=b'Can be sold')),
                ('purchase_ok', models.BooleanField(verbose_name=b'Can be purchased')),
                ('image', models.ImageField(blank=True, upload_to=b'')),
                ('product_type', models.CharField(blank=True, choices=[(b'stockable', b'Stockable'), (b'consumable', b'Consumable'), (b'service', b'Service')], max_length=12, verbose_name=b'Product Type')),
                ('sale_price', models.FloatField(blank=True, verbose_name=b'Sale Price')),
                ('cost_price', models.FloatField(blank=True, verbose_name=b'Cost Price')),
                ('product_status', models.CharField(blank=True, choices=[(b'development', b'In developemt'), (b'normal', b'Normal'), (b'end', b'End of Life Cycle'), (b'obsolete', b'Obsolote')], max_length=10, verbose_name=b'Status')),
                ('description', models.TextField(verbose_name=b'Product Description')),
                ('quantity_on_hand', models.IntegerField(blank=True, verbose_name=b'Quantity On Hand')),
                ('rack', models.CharField(blank=True, max_length=100, verbose_name=b'Rack')),
                ('row', models.CharField(blank=True, max_length=100, verbose_name=b'Row')),
                ('case', models.CharField(blank=True, max_length=100, verbose_name=b'Case')),
                ('warranty', models.DurationField(verbose_name=b'Warranty')),
                ('lead_time', models.DurationField(verbose_name=b'Customer Lead TIme')),
                ('description_purchase', models.TextField(verbose_name=b'Purchase Description')),
                ('description_sale', models.TextField(verbose_name=b'Sales Description')),
                ('product_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
