# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Unit of measure')),
                ('unit', models.CharField(choices=[(b'unit', b'Unit'), (b'weight', b'Weight'), (b'volume', b'Volume'), (b'length', b'Length'), (b'time', b'Time')], max_length=50, verbose_name=b'Unit category')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Product Manager'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ProductUOM'),
        ),
    ]
