# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Company')),
                ('mobile', models.BigIntegerField(verbose_name='Mobile')),
                ('phone', models.BigIntegerField(verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('street', models.CharField(max_length=300, verbose_name='Lane')),
                ('street2', models.CharField(max_length=300, verbose_name='Street')),
                ('city', models.CharField(max_length=250, null=True, verbose_name='City')),
                ('note', models.TextField(null=True, verbose_name='Internal Note')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='State')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=250, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='note',
            field=models.TextField(null=True, verbose_name='Internal Note'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=300, null=True, verbose_name='Lane'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street2',
            field=models.CharField(max_length=300, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.State', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.State', verbose_name='State'),
        ),
    ]
