# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-25 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170323_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to=b'', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=250, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile',
            field=models.BigIntegerField(blank=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='note',
            field=models.TextField(blank=True, verbose_name='Internal Note'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.BigIntegerField(blank=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, max_length=300, verbose_name='Lane'),
        ),
        migrations.AlterField(
            model_name='company',
            name='street2',
            field=models.CharField(blank=True, max_length=300, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=250, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.BigIntegerField(blank=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, verbose_name='Internal Note'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, max_length=300, verbose_name='Lane'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street2',
            field=models.CharField(blank=True, max_length=300, verbose_name='Street'),
        ),
    ]
