# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170325_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
