# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_company',
            field=models.BooleanField(verbose_name='Is comapany'),
        ),
    ]
