# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170403_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
