# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20170408_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='zip',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip Code'),
        ),
    ]
